#!/usr/bin/env bash
set -e

echo "Starting container…"

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# Wait for DB
wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

# # Optional DB creation
# if [ "${RUN_CREATE_DB}" = "1" ] || [ "${RUN_CREATE_DB}" = "true" ]; then
#     echo "running create_database.py"
#     python database_creation/create_database.py --create-db --fake-data --dsn "${DATABASE_URL}"
# else
#     echo "skipping database creation"
# fi

exec "$@"