# Generated by Django 6.0.1 on 2026-01-06 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('did', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Discord ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='base.group')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='GeneralRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField()),
                ('person', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
            options={
                'verbose_name': 'General Role',
                'verbose_name_plural': 'General Roles',
                'db_table': 'general_role',
            },
        ),
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('assigned', models.ForeignKey(blank=True, db_column='assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.person')),
            ],
            options={
                'verbose_name': 'Reach',
                'verbose_name_plural': 'Reaches',
                'db_table': 'reaches',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.CASCADE, to='base.event')),
                ('person', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'db_table': 'event_participants',
                'unique_together': {('event', 'person')},
            },
        ),
        migrations.CreateModel(
            name='AssignedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='base.person')),
                ('tag', models.ForeignKey(db_column='tid', on_delete=django.db.models.deletion.CASCADE, to='base.tag')),
            ],
            options={
                'verbose_name': 'Assigned Tag',
                'verbose_name_plural': 'Assigned Tags',
                'db_table': 'assigned_tags',
                'unique_together': {('person', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField()),
                ('group', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='base.group')),
                ('person', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
            options={
                'verbose_name': 'Volunteer in Group',
                'verbose_name_plural': 'Volunteers in Groups',
                'db_table': 'volunteer_in_groups',
                'unique_together': {('person', 'group')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.CharField(max_length=255)),
                ('response', models.IntegerField(choices=[(1, 'Accepted'), (0, 'Declined')])),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='base.reach')),
            ],
            options={
                'db_table': 'volunteer_responses',
                'unique_together': {('did', 'rid')},
            },
        ),
    ]
